#include <arv.h>
#include <stdlib.h>
#include <signal.h>
#include <stdio.h>

#define EXPECT_BPP(FORMAT, NUM) {\
if (ARV_PIXEL_FORMAT_BIT_PER_PIXEL(FORMAT) != NUM) {\
    printf("ARV_PIXEL_FORMAT_BIT_PER_PIXEL failed for %s: expected %d but got %d\n", #FORMAT, NUM, ARV_PIXEL_FORMAT_BIT_PER_PIXEL(FORMAT)); \
    return 0;\
}\
}

/**
 * @brief test_bit_per_pixel checks the macro ARV_PIXEL_FORMAT_BIT_PER_PIXEL.
 * Note that this macro gives the number of bits used for transmitting a pixel value,
 * which may be higher than the underlying sensor's bit depth.
 *
 * @return 1 if all tests succeed, otherwise 0.
 */
int test_bit_per_pixel() {
    EXPECT_BPP(ARV_PIXEL_FORMAT_MONO_8, 8);
    EXPECT_BPP(ARV_PIXEL_FORMAT_MONO_8_SIGNED, 8);
    EXPECT_BPP(ARV_PIXEL_FORMAT_BAYER_GR_8, 8)
    EXPECT_BPP(ARV_PIXEL_FORMAT_BAYER_RG_8, 8)
    EXPECT_BPP(ARV_PIXEL_FORMAT_BAYER_GB_8, 8)
    EXPECT_BPP(ARV_PIXEL_FORMAT_BAYER_BG_8, 8)

    EXPECT_BPP(ARV_PIXEL_FORMAT_MONO_10, 16)
    EXPECT_BPP(ARV_PIXEL_FORMAT_MONO_12, 16)
    EXPECT_BPP(ARV_PIXEL_FORMAT_MONO_14, 16)
    EXPECT_BPP(ARV_PIXEL_FORMAT_MONO_16, 16)


    EXPECT_BPP(ARV_PIXEL_FORMAT_BAYER_GR_10, 16)
    EXPECT_BPP(ARV_PIXEL_FORMAT_BAYER_RG_10, 16)
    EXPECT_BPP(ARV_PIXEL_FORMAT_BAYER_GB_10, 16)
    EXPECT_BPP(ARV_PIXEL_FORMAT_BAYER_BG_10, 16)

    EXPECT_BPP(ARV_PIXEL_FORMAT_BAYER_GR_12, 16)
    EXPECT_BPP(ARV_PIXEL_FORMAT_BAYER_RG_12, 16)
    EXPECT_BPP(ARV_PIXEL_FORMAT_BAYER_GB_12, 16)
    EXPECT_BPP(ARV_PIXEL_FORMAT_BAYER_BG_12, 16)

    EXPECT_BPP(ARV_PIXEL_FORMAT_BAYER_GR_16, 16)
    EXPECT_BPP(ARV_PIXEL_FORMAT_BAYER_RG_16, 16)
    EXPECT_BPP(ARV_PIXEL_FORMAT_BAYER_GB_16, 16)
    EXPECT_BPP(ARV_PIXEL_FORMAT_BAYER_BG_16, 16)

    EXPECT_BPP(ARV_PIXEL_FORMAT_MONO_10_PACKED, 12)

    EXPECT_BPP(ARV_PIXEL_FORMAT_BAYER_BG_10P, 10)
    EXPECT_BPP(ARV_PIXEL_FORMAT_BAYER_GB_10P, 10)
    EXPECT_BPP(ARV_PIXEL_FORMAT_BAYER_GR_10P, 10)
    EXPECT_BPP(ARV_PIXEL_FORMAT_BAYER_RG_10P, 10)
    
    EXPECT_BPP(ARV_PIXEL_FORMAT_BAYER_GR_10_PACKED, 12)
    EXPECT_BPP(ARV_PIXEL_FORMAT_BAYER_RG_10_PACKED, 12)
    EXPECT_BPP(ARV_PIXEL_FORMAT_BAYER_GB_10_PACKED, 12)
    EXPECT_BPP(ARV_PIXEL_FORMAT_BAYER_BG_10_PACKED, 12)

    EXPECT_BPP(ARV_PIXEL_FORMAT_MONO_12_PACKED, 12)

    EXPECT_BPP(ARV_PIXEL_FORMAT_BAYER_BG_12P, 12)
    EXPECT_BPP(ARV_PIXEL_FORMAT_BAYER_GB_12P, 12)
    EXPECT_BPP(ARV_PIXEL_FORMAT_BAYER_GR_12P, 12)
    EXPECT_BPP(ARV_PIXEL_FORMAT_BAYER_RG_12P, 12)

    EXPECT_BPP(ARV_PIXEL_FORMAT_BAYER_GR_12_PACKED, 12)
    EXPECT_BPP(ARV_PIXEL_FORMAT_BAYER_RG_12_PACKED, 12)
    EXPECT_BPP(ARV_PIXEL_FORMAT_BAYER_GB_12_PACKED, 12)
    EXPECT_BPP(ARV_PIXEL_FORMAT_BAYER_BG_12_PACKED, 12)

    return 1;
}

#define EXPECT_8_BIT(FORMAT) {\
if (!ARV_PIXEL_FORMAT_8_BIT(FORMAT)) {\
    printf("ARV_PIXEL_FORMAT_8_BIT failed for %s: expected true but got false\n", #FORMAT); \
    success = 0;\
}\
}

#define EXPECT_NOT_8_BIT(FORMAT) {\
if (ARV_PIXEL_FORMAT_8_BIT(FORMAT)) {\
    printf("ARV_PIXEL_FORMAT_8_BIT failed for %s: expected false but got true\n", #FORMAT); \
    success = 0;\
}\
}

/**
 * @brief test_8bit tests the macro ARV_PIXEL_FORMAT_8_BIT
 * @return
 */
int test_8bit() {
    int success = 1;
    EXPECT_8_BIT(ARV_PIXEL_FORMAT_MONO_8);
    EXPECT_8_BIT(ARV_PIXEL_FORMAT_MONO_8_SIGNED);
    EXPECT_8_BIT(ARV_PIXEL_FORMAT_BAYER_GR_8);
    EXPECT_8_BIT(ARV_PIXEL_FORMAT_BAYER_RG_8);
    EXPECT_8_BIT(ARV_PIXEL_FORMAT_BAYER_GB_8);
    EXPECT_8_BIT(ARV_PIXEL_FORMAT_BAYER_BG_8);
    EXPECT_8_BIT(ARV_PIXEL_FORMAT_RGB_8_PACKED);
    EXPECT_8_BIT(ARV_PIXEL_FORMAT_BGR_8_PACKED);
    EXPECT_8_BIT(ARV_PIXEL_FORMAT_RGB_8_PLANAR);

    EXPECT_NOT_8_BIT(ARV_PIXEL_FORMAT_MONO_10);
    EXPECT_NOT_8_BIT(ARV_PIXEL_FORMAT_MONO_10_PACKED);
    EXPECT_NOT_8_BIT(ARV_PIXEL_FORMAT_MONO_12);
    EXPECT_NOT_8_BIT(ARV_PIXEL_FORMAT_MONO_12_PACKED);
    EXPECT_NOT_8_BIT(ARV_PIXEL_FORMAT_MONO_14);
    EXPECT_NOT_8_BIT(ARV_PIXEL_FORMAT_MONO_16);
    EXPECT_NOT_8_BIT(ARV_PIXEL_FORMAT_BAYER_GR_10);
    EXPECT_NOT_8_BIT(ARV_PIXEL_FORMAT_BAYER_RG_10);
    EXPECT_NOT_8_BIT(ARV_PIXEL_FORMAT_BAYER_GB_10);
    EXPECT_NOT_8_BIT(ARV_PIXEL_FORMAT_BAYER_BG_10);
    EXPECT_NOT_8_BIT(ARV_PIXEL_FORMAT_BAYER_GR_12);
    EXPECT_NOT_8_BIT(ARV_PIXEL_FORMAT_BAYER_RG_12);
    EXPECT_NOT_8_BIT(ARV_PIXEL_FORMAT_BAYER_GB_12);
    EXPECT_NOT_8_BIT(ARV_PIXEL_FORMAT_BAYER_BG_12);
    EXPECT_NOT_8_BIT(ARV_PIXEL_FORMAT_BAYER_GR_16);
    EXPECT_NOT_8_BIT(ARV_PIXEL_FORMAT_BAYER_RG_16);
    EXPECT_NOT_8_BIT(ARV_PIXEL_FORMAT_BAYER_GB_16);
    EXPECT_NOT_8_BIT(ARV_PIXEL_FORMAT_BAYER_BG_16);
    EXPECT_NOT_8_BIT(ARV_PIXEL_FORMAT_BAYER_BG_10P);
    EXPECT_NOT_8_BIT(ARV_PIXEL_FORMAT_BAYER_GB_10P);
    EXPECT_NOT_8_BIT(ARV_PIXEL_FORMAT_BAYER_GR_10P);
    EXPECT_NOT_8_BIT(ARV_PIXEL_FORMAT_BAYER_RG_10P);
    EXPECT_NOT_8_BIT(ARV_PIXEL_FORMAT_BAYER_BG_12P);
    EXPECT_NOT_8_BIT(ARV_PIXEL_FORMAT_BAYER_GB_12P);
    EXPECT_NOT_8_BIT(ARV_PIXEL_FORMAT_BAYER_GR_12P);
    EXPECT_NOT_8_BIT(ARV_PIXEL_FORMAT_BAYER_RG_12P);
    EXPECT_NOT_8_BIT(ARV_PIXEL_FORMAT_BAYER_GR_12_PACKED);
    EXPECT_NOT_8_BIT(ARV_PIXEL_FORMAT_BAYER_RG_12_PACKED);
    EXPECT_NOT_8_BIT(ARV_PIXEL_FORMAT_BAYER_GB_12_PACKED);
    EXPECT_NOT_8_BIT(ARV_PIXEL_FORMAT_BAYER_BG_12_PACKED);
    EXPECT_NOT_8_BIT(ARV_PIXEL_FORMAT_BAYER_GR_10_PACKED);
    EXPECT_NOT_8_BIT(ARV_PIXEL_FORMAT_BAYER_RG_10_PACKED);
    EXPECT_NOT_8_BIT(ARV_PIXEL_FORMAT_BAYER_GB_10_PACKED);
    EXPECT_NOT_8_BIT(ARV_PIXEL_FORMAT_BAYER_BG_10_PACKED);
    EXPECT_NOT_8_BIT(ARV_PIXEL_FORMAT_RGB_10_PACKED);
    EXPECT_NOT_8_BIT(ARV_PIXEL_FORMAT_BGR_10_PACKED);
    EXPECT_NOT_8_BIT(ARV_PIXEL_FORMAT_RGB_12_PACKED);
    EXPECT_NOT_8_BIT(ARV_PIXEL_FORMAT_BGR_12_PACKED);
    EXPECT_NOT_8_BIT(ARV_PIXEL_FORMAT_MONO_10);
    EXPECT_NOT_8_BIT(ARV_PIXEL_FORMAT_MONO_10);
    EXPECT_NOT_8_BIT(ARV_PIXEL_FORMAT_MONO_10);
    EXPECT_NOT_8_BIT(ARV_PIXEL_FORMAT_MONO_10);
    EXPECT_NOT_8_BIT(ARV_PIXEL_FORMAT_MONO_10);
    EXPECT_NOT_8_BIT(ARV_PIXEL_FORMAT_MONO_10);
    EXPECT_NOT_8_BIT(ARV_PIXEL_FORMAT_MONO_10);
    EXPECT_NOT_8_BIT(ARV_PIXEL_FORMAT_MONO_10);
    EXPECT_NOT_8_BIT(ARV_PIXEL_FORMAT_MONO_10);
    return success;
}

#define EXPECT_10_BIT(FORMAT) {\
if (!ARV_PIXEL_FORMAT_10_BIT(FORMAT)) {\
    printf("ARV_PIXEL_FORMAT_10_BIT failed for %s: expected true but got false\n", #FORMAT); \
    success = 0;\
}\
}

#define EXPECT_NOT_10_BIT(FORMAT) {\
if (ARV_PIXEL_FORMAT_10_BIT(FORMAT)) {\
    printf("ARV_PIXEL_FORMAT_10_BIT failed for %s: expected false but got true\n", #FORMAT); \
    success = 0;\
}\
}

int test_10bit() {
    int success = 1;
    EXPECT_10_BIT(ARV_PIXEL_FORMAT_MONO_10);
    EXPECT_10_BIT(ARV_PIXEL_FORMAT_MONO_10_PACKED);
    EXPECT_10_BIT(ARV_PIXEL_FORMAT_BAYER_GR_10);
    EXPECT_10_BIT(ARV_PIXEL_FORMAT_BAYER_RG_10);
    EXPECT_10_BIT(ARV_PIXEL_FORMAT_BAYER_GB_10);
    EXPECT_10_BIT(ARV_PIXEL_FORMAT_BAYER_BG_10);
    EXPECT_10_BIT(ARV_PIXEL_FORMAT_BAYER_BG_10P);
    EXPECT_10_BIT(ARV_PIXEL_FORMAT_BAYER_GB_10P);
    EXPECT_10_BIT(ARV_PIXEL_FORMAT_BAYER_GR_10P);
    EXPECT_10_BIT(ARV_PIXEL_FORMAT_BAYER_RG_10P);
    EXPECT_10_BIT(ARV_PIXEL_FORMAT_BAYER_GR_10_PACKED);
    EXPECT_10_BIT(ARV_PIXEL_FORMAT_BAYER_RG_10_PACKED);
    EXPECT_10_BIT(ARV_PIXEL_FORMAT_BAYER_GB_10_PACKED);
    EXPECT_10_BIT(ARV_PIXEL_FORMAT_BAYER_BG_10_PACKED);

    // These two fail since they don't have a common bit with all the other 10bit types.
    EXPECT_10_BIT(ARV_PIXEL_FORMAT_RGB_10_PACKED);
    EXPECT_10_BIT(ARV_PIXEL_FORMAT_BGR_10_PACKED);

    EXPECT_NOT_10_BIT(ARV_PIXEL_FORMAT_MONO_8);
    EXPECT_NOT_10_BIT(ARV_PIXEL_FORMAT_MONO_8_SIGNED);
    EXPECT_NOT_10_BIT(ARV_PIXEL_FORMAT_MONO_12);
    EXPECT_NOT_10_BIT(ARV_PIXEL_FORMAT_MONO_12_PACKED);
    EXPECT_NOT_10_BIT(ARV_PIXEL_FORMAT_MONO_14);
    EXPECT_NOT_10_BIT(ARV_PIXEL_FORMAT_MONO_16);
    EXPECT_NOT_10_BIT(ARV_PIXEL_FORMAT_BAYER_GR_8);
    EXPECT_NOT_10_BIT(ARV_PIXEL_FORMAT_BAYER_RG_8);
    EXPECT_NOT_10_BIT(ARV_PIXEL_FORMAT_BAYER_GB_8);
    EXPECT_NOT_10_BIT(ARV_PIXEL_FORMAT_BAYER_BG_8);
    EXPECT_NOT_10_BIT(ARV_PIXEL_FORMAT_BAYER_GR_12);
    EXPECT_NOT_10_BIT(ARV_PIXEL_FORMAT_BAYER_RG_12);
    EXPECT_NOT_10_BIT(ARV_PIXEL_FORMAT_BAYER_GB_12);
    EXPECT_NOT_10_BIT(ARV_PIXEL_FORMAT_BAYER_BG_12);
    EXPECT_NOT_10_BIT(ARV_PIXEL_FORMAT_BAYER_GR_16);
    EXPECT_NOT_10_BIT(ARV_PIXEL_FORMAT_BAYER_RG_16);
    EXPECT_NOT_10_BIT(ARV_PIXEL_FORMAT_BAYER_GB_16);
    EXPECT_NOT_10_BIT(ARV_PIXEL_FORMAT_BAYER_BG_16);
    EXPECT_NOT_10_BIT(ARV_PIXEL_FORMAT_BAYER_BG_12P);
    EXPECT_NOT_10_BIT(ARV_PIXEL_FORMAT_BAYER_GB_12P);
    EXPECT_NOT_10_BIT(ARV_PIXEL_FORMAT_BAYER_GR_12P);
    EXPECT_NOT_10_BIT(ARV_PIXEL_FORMAT_BAYER_RG_12P);
    EXPECT_NOT_10_BIT(ARV_PIXEL_FORMAT_BAYER_GR_12_PACKED);
    EXPECT_NOT_10_BIT(ARV_PIXEL_FORMAT_BAYER_RG_12_PACKED);
    EXPECT_NOT_10_BIT(ARV_PIXEL_FORMAT_BAYER_GB_12_PACKED);
    EXPECT_NOT_10_BIT(ARV_PIXEL_FORMAT_BAYER_BG_12_PACKED);
    EXPECT_NOT_10_BIT(ARV_PIXEL_FORMAT_RGB_8_PACKED);
    EXPECT_NOT_10_BIT(ARV_PIXEL_FORMAT_BGR_8_PACKED);
    EXPECT_NOT_10_BIT(ARV_PIXEL_FORMAT_RGBA_8_PACKED);
    EXPECT_NOT_10_BIT(ARV_PIXEL_FORMAT_BGRA_8_PACKED);

    if (!success) {
        printf("End of messages for test_10bit\n");
    }

    return success;
}


#define EXPECT_12_BIT(FORMAT) {\
if (!ARV_PIXEL_FORMAT_12_BIT(FORMAT)) {\
    printf("ARV_PIXEL_FORMAT_12_BIT failed for %s: expected true but got false\n", #FORMAT); \
    failure++;\
}\
}

#define EXPECT_NOT_12_BIT(FORMAT) {\
if (ARV_PIXEL_FORMAT_12_BIT(FORMAT)) {\
    printf("ARV_PIXEL_FORMAT_12_BIT failed for %s: expected false but got true\n", #FORMAT); \
    failure++;\
}\
}

int test_12bit() {
    int failure = 0;
    EXPECT_12_BIT(ARV_PIXEL_FORMAT_MONO_12);
    EXPECT_12_BIT(ARV_PIXEL_FORMAT_MONO_12_PACKED);
    EXPECT_12_BIT(ARV_PIXEL_FORMAT_BAYER_GR_12);
    EXPECT_12_BIT(ARV_PIXEL_FORMAT_BAYER_RG_12);
    EXPECT_12_BIT(ARV_PIXEL_FORMAT_BAYER_GB_12);
    EXPECT_12_BIT(ARV_PIXEL_FORMAT_BAYER_BG_12);
    EXPECT_12_BIT(ARV_PIXEL_FORMAT_BAYER_BG_12P);
    EXPECT_12_BIT(ARV_PIXEL_FORMAT_BAYER_GB_12P);
    EXPECT_12_BIT(ARV_PIXEL_FORMAT_BAYER_GR_12P);
    EXPECT_12_BIT(ARV_PIXEL_FORMAT_BAYER_RG_12P);
    EXPECT_12_BIT(ARV_PIXEL_FORMAT_BAYER_GR_12_PACKED);
    EXPECT_12_BIT(ARV_PIXEL_FORMAT_BAYER_RG_12_PACKED);
    EXPECT_12_BIT(ARV_PIXEL_FORMAT_BAYER_GB_12_PACKED);
    EXPECT_12_BIT(ARV_PIXEL_FORMAT_BAYER_BG_12_PACKED);

    // These two fail since they don't have a common bit with all the other 12bit types.
    EXPECT_12_BIT(ARV_PIXEL_FORMAT_RGB_12_PACKED);
    EXPECT_12_BIT(ARV_PIXEL_FORMAT_BGR_12_PACKED);

    EXPECT_NOT_12_BIT(ARV_PIXEL_FORMAT_MONO_8);
    EXPECT_NOT_12_BIT(ARV_PIXEL_FORMAT_MONO_8_SIGNED);
    EXPECT_NOT_12_BIT(ARV_PIXEL_FORMAT_MONO_10);
    EXPECT_NOT_12_BIT(ARV_PIXEL_FORMAT_MONO_10_PACKED);
    EXPECT_NOT_12_BIT(ARV_PIXEL_FORMAT_MONO_14);
    EXPECT_NOT_12_BIT(ARV_PIXEL_FORMAT_MONO_16);
    EXPECT_NOT_12_BIT(ARV_PIXEL_FORMAT_BAYER_GR_8);
    EXPECT_NOT_12_BIT(ARV_PIXEL_FORMAT_BAYER_RG_8);
    EXPECT_NOT_12_BIT(ARV_PIXEL_FORMAT_BAYER_GB_8);
    EXPECT_NOT_12_BIT(ARV_PIXEL_FORMAT_BAYER_BG_8);
    EXPECT_NOT_12_BIT(ARV_PIXEL_FORMAT_BAYER_GR_10);
    EXPECT_NOT_12_BIT(ARV_PIXEL_FORMAT_BAYER_RG_10);
    EXPECT_NOT_12_BIT(ARV_PIXEL_FORMAT_BAYER_GB_10);
    EXPECT_NOT_12_BIT(ARV_PIXEL_FORMAT_BAYER_BG_10);
    EXPECT_NOT_12_BIT(ARV_PIXEL_FORMAT_BAYER_GR_16);
    EXPECT_NOT_12_BIT(ARV_PIXEL_FORMAT_BAYER_RG_16);
    EXPECT_NOT_12_BIT(ARV_PIXEL_FORMAT_BAYER_GB_16);
    EXPECT_NOT_12_BIT(ARV_PIXEL_FORMAT_BAYER_BG_16);
    EXPECT_NOT_12_BIT(ARV_PIXEL_FORMAT_BAYER_BG_10P);
    EXPECT_NOT_12_BIT(ARV_PIXEL_FORMAT_BAYER_GB_10P);
    EXPECT_NOT_12_BIT(ARV_PIXEL_FORMAT_BAYER_GR_10P);
    EXPECT_NOT_12_BIT(ARV_PIXEL_FORMAT_BAYER_RG_10P);
    EXPECT_NOT_12_BIT(ARV_PIXEL_FORMAT_BAYER_GR_10_PACKED);
    EXPECT_NOT_12_BIT(ARV_PIXEL_FORMAT_BAYER_RG_10_PACKED);
    EXPECT_NOT_12_BIT(ARV_PIXEL_FORMAT_BAYER_GB_10_PACKED);
    EXPECT_NOT_12_BIT(ARV_PIXEL_FORMAT_BAYER_BG_10_PACKED);
    EXPECT_NOT_12_BIT(ARV_PIXEL_FORMAT_RGB_8_PACKED);
    EXPECT_NOT_12_BIT(ARV_PIXEL_FORMAT_BGR_8_PACKED);
    EXPECT_NOT_12_BIT(ARV_PIXEL_FORMAT_RGBA_8_PACKED);
    EXPECT_NOT_12_BIT(ARV_PIXEL_FORMAT_BGRA_8_PACKED);

    if (failure) {
        printf("End of messages for test_12bit, got %d fails \n\n", failure);
    }
    return !failure;
}

void print_bits(ArvPixelFormat fmt) {
    for (int ii = 0; ii < 32; ++ii) {
        printf("%d", (fmt >> (31-ii)) & 1);
    }
}

void print_common_8bit() {
    ArvPixelFormat fmt = ARV_PIXEL_FORMAT_MONO_8;
    fmt &= ARV_PIXEL_FORMAT_MONO_8_SIGNED;
    fmt &= ARV_PIXEL_FORMAT_BAYER_GR_8;
    fmt &= ARV_PIXEL_FORMAT_BAYER_RG_8;
    fmt &= ARV_PIXEL_FORMAT_BAYER_GB_8;
    fmt &= ARV_PIXEL_FORMAT_BAYER_BG_8;
    fmt &= ARV_PIXEL_FORMAT_RGB_8_PACKED;
    fmt &= ARV_PIXEL_FORMAT_BGR_8_PACKED;
    fmt &= ARV_PIXEL_FORMAT_RGB_8_PLANAR;

    ArvPixelFormat fmt_union = ARV_PIXEL_FORMAT_MONO_8;
    fmt_union |= ARV_PIXEL_FORMAT_MONO_8_SIGNED;
    fmt_union |= ARV_PIXEL_FORMAT_BAYER_GR_8;
    fmt_union |= ARV_PIXEL_FORMAT_BAYER_RG_8;
    fmt_union |= ARV_PIXEL_FORMAT_BAYER_GB_8;
    fmt_union |= ARV_PIXEL_FORMAT_BAYER_BG_8;
    fmt_union |= ARV_PIXEL_FORMAT_RGB_8_PACKED;
    fmt_union |= ARV_PIXEL_FORMAT_BGR_8_PACKED;
    fmt_union |= ARV_PIXEL_FORMAT_RGB_8_PLANAR;

    printf("common bits in 8bit pixel formats: ");
    print_bits(fmt);
    printf("\n" "mask: 0x%08x\n", fmt);
    printf("union of bits in 8bit pixel formats: ");
    print_bits(fmt_union);
    printf("\n" "mask: 0x%08x\n\n", fmt_union);
}

void print_common_10bit() {
    ArvPixelFormat fmt = ARV_PIXEL_FORMAT_MONO_10;
    fmt &= ARV_PIXEL_FORMAT_MONO_10_PACKED;
    fmt &= ARV_PIXEL_FORMAT_BAYER_GR_10;
    fmt &= ARV_PIXEL_FORMAT_BAYER_RG_10;
    fmt &= ARV_PIXEL_FORMAT_BAYER_GB_10;
    fmt &= ARV_PIXEL_FORMAT_BAYER_BG_10;
    fmt &= ARV_PIXEL_FORMAT_BAYER_GR_10P;
    fmt &= ARV_PIXEL_FORMAT_BAYER_RG_10P;
    fmt &= ARV_PIXEL_FORMAT_BAYER_GB_10P;
    fmt &= ARV_PIXEL_FORMAT_BAYER_BG_10P;
    fmt &= ARV_PIXEL_FORMAT_BAYER_GR_10_PACKED;
    fmt &= ARV_PIXEL_FORMAT_BAYER_RG_10_PACKED;
    fmt &= ARV_PIXEL_FORMAT_BAYER_GB_10_PACKED;
    fmt &= ARV_PIXEL_FORMAT_BAYER_BG_10_PACKED;

    ArvPixelFormat fmt_union = ARV_PIXEL_FORMAT_MONO_10;
    fmt_union |= ARV_PIXEL_FORMAT_MONO_10_PACKED;
    fmt_union |= ARV_PIXEL_FORMAT_BAYER_GR_10;
    fmt_union |= ARV_PIXEL_FORMAT_BAYER_RG_10;
    fmt_union |= ARV_PIXEL_FORMAT_BAYER_GB_10;
    fmt_union |= ARV_PIXEL_FORMAT_BAYER_BG_10;
    fmt_union |= ARV_PIXEL_FORMAT_BAYER_GR_10P;
    fmt_union |= ARV_PIXEL_FORMAT_BAYER_RG_10P;
    fmt_union |= ARV_PIXEL_FORMAT_BAYER_GB_10P;
    fmt_union |= ARV_PIXEL_FORMAT_BAYER_BG_10P;
    fmt_union |= ARV_PIXEL_FORMAT_BAYER_GR_10_PACKED;
    fmt_union |= ARV_PIXEL_FORMAT_BAYER_RG_10_PACKED;
    fmt_union |= ARV_PIXEL_FORMAT_BAYER_GB_10_PACKED;
    fmt_union |= ARV_PIXEL_FORMAT_BAYER_BG_10_PACKED;

    printf("common bits in 10bit pixel formats: ");
    print_bits(fmt);
    printf("\n" "mask: 0x%08x\n", fmt);
    printf("union of bits in 10bit pixel formats: ");
    print_bits(fmt_union);
    printf("\n" "mask: 0x%08x\n\n", fmt_union);
}

void print_common_12bit() {
    ArvPixelFormat fmt = ARV_PIXEL_FORMAT_MONO_12;
    fmt &= ARV_PIXEL_FORMAT_MONO_12_PACKED;
    fmt &= ARV_PIXEL_FORMAT_BAYER_GR_12;
    fmt &= ARV_PIXEL_FORMAT_BAYER_RG_12;
    fmt &= ARV_PIXEL_FORMAT_BAYER_GB_12;
    fmt &= ARV_PIXEL_FORMAT_BAYER_BG_12;
    fmt &= ARV_PIXEL_FORMAT_BAYER_GR_12P;
    fmt &= ARV_PIXEL_FORMAT_BAYER_RG_12P;
    fmt &= ARV_PIXEL_FORMAT_BAYER_GB_12P;
    fmt &= ARV_PIXEL_FORMAT_BAYER_BG_12P;
    fmt &= ARV_PIXEL_FORMAT_BAYER_GR_12_PACKED;
    fmt &= ARV_PIXEL_FORMAT_BAYER_RG_12_PACKED;
    fmt &= ARV_PIXEL_FORMAT_BAYER_GB_12_PACKED;
    fmt &= ARV_PIXEL_FORMAT_BAYER_BG_12_PACKED;

    ArvPixelFormat fmt_union = ARV_PIXEL_FORMAT_MONO_12;
    fmt_union |= ARV_PIXEL_FORMAT_MONO_12_PACKED;
    fmt_union |= ARV_PIXEL_FORMAT_BAYER_GR_12;
    fmt_union |= ARV_PIXEL_FORMAT_BAYER_RG_12;
    fmt_union |= ARV_PIXEL_FORMAT_BAYER_GB_12;
    fmt_union |= ARV_PIXEL_FORMAT_BAYER_BG_12;
    fmt_union |= ARV_PIXEL_FORMAT_BAYER_GR_12P;
    fmt_union |= ARV_PIXEL_FORMAT_BAYER_RG_12P;
    fmt_union |= ARV_PIXEL_FORMAT_BAYER_GB_12P;
    fmt_union |= ARV_PIXEL_FORMAT_BAYER_BG_12P;
    fmt_union |= ARV_PIXEL_FORMAT_BAYER_GR_12_PACKED;
    fmt_union |= ARV_PIXEL_FORMAT_BAYER_RG_12_PACKED;
    fmt_union |= ARV_PIXEL_FORMAT_BAYER_GB_12_PACKED;
    fmt_union |= ARV_PIXEL_FORMAT_BAYER_BG_12_PACKED;

    printf("common bits in 12bit pixel formats: ");
    print_bits(fmt);
    printf("\n" "mask: 0x%08x\n", fmt);
    printf("union of bits in 12bit pixel formats: ");
    print_bits(fmt_union);
    printf("\n" "mask: 0x%08x\n\n", fmt_union);
}

void print_common_packed() {
    ArvPixelFormat fmt = ARV_PIXEL_FORMAT_MONO_10_PACKED;
    fmt &= ARV_PIXEL_FORMAT_MONO_12_PACKED;
    fmt &= ARV_PIXEL_FORMAT_BAYER_GR_10P;
    fmt &= ARV_PIXEL_FORMAT_BAYER_RG_10P;
    fmt &= ARV_PIXEL_FORMAT_BAYER_GB_10P;
    fmt &= ARV_PIXEL_FORMAT_BAYER_BG_10P;
    fmt &= ARV_PIXEL_FORMAT_BAYER_GR_10_PACKED;
    fmt &= ARV_PIXEL_FORMAT_BAYER_RG_10_PACKED;
    fmt &= ARV_PIXEL_FORMAT_BAYER_GB_10_PACKED;
    fmt &= ARV_PIXEL_FORMAT_BAYER_BG_10_PACKED;
    fmt &= ARV_PIXEL_FORMAT_BAYER_BG_12P;
    fmt &= ARV_PIXEL_FORMAT_BAYER_GB_12P;
    fmt &= ARV_PIXEL_FORMAT_BAYER_GR_12P;
    fmt &= ARV_PIXEL_FORMAT_BAYER_RG_12P;
    fmt &= ARV_PIXEL_FORMAT_BAYER_GR_12_PACKED;
    fmt &= ARV_PIXEL_FORMAT_BAYER_RG_12_PACKED;
    fmt &= ARV_PIXEL_FORMAT_BAYER_GB_12_PACKED;
    fmt &= ARV_PIXEL_FORMAT_BAYER_BG_12_PACKED;
    fmt &= ARV_PIXEL_FORMAT_RGB_8_PACKED;
    fmt &= ARV_PIXEL_FORMAT_BGR_8_PACKED;

    ArvPixelFormat fmt_union = ARV_PIXEL_FORMAT_MONO_10_PACKED;
    fmt_union |= ARV_PIXEL_FORMAT_MONO_12_PACKED;
    fmt_union |= ARV_PIXEL_FORMAT_BAYER_GR_10P;
    fmt_union |= ARV_PIXEL_FORMAT_BAYER_RG_10P;
    fmt_union |= ARV_PIXEL_FORMAT_BAYER_GB_10P;
    fmt_union |= ARV_PIXEL_FORMAT_BAYER_BG_10P;
    fmt_union |= ARV_PIXEL_FORMAT_BAYER_GR_10_PACKED;
    fmt_union |= ARV_PIXEL_FORMAT_BAYER_RG_10_PACKED;
    fmt_union |= ARV_PIXEL_FORMAT_BAYER_GB_10_PACKED;
    fmt_union |= ARV_PIXEL_FORMAT_BAYER_BG_10_PACKED;
    fmt_union |= ARV_PIXEL_FORMAT_BAYER_BG_12P;
    fmt_union |= ARV_PIXEL_FORMAT_BAYER_GB_12P;
    fmt_union |= ARV_PIXEL_FORMAT_BAYER_GR_12P;
    fmt_union |= ARV_PIXEL_FORMAT_BAYER_RG_12P;
    fmt_union |= ARV_PIXEL_FORMAT_BAYER_GR_12_PACKED;
    fmt_union |= ARV_PIXEL_FORMAT_BAYER_RG_12_PACKED;
    fmt_union |= ARV_PIXEL_FORMAT_BAYER_GB_12_PACKED;
    fmt_union |= ARV_PIXEL_FORMAT_BAYER_BG_12_PACKED;
    fmt_union |= ARV_PIXEL_FORMAT_RGB_8_PACKED;
    fmt &= ARV_PIXEL_FORMAT_BGR_8_PACKED;

    printf("common bits in packed pixel formats: ");
    print_bits(fmt);
    printf("\n" "mask: 0x%08x\n", fmt);
    printf("union of bits in packed pixel formats: ");
    print_bits(fmt_union);
    printf("\n" "mask: 0x%08x\n\n", fmt_union);
}

int
main (int argc, char **argv) {
    int num_fail = 0;
    int num_total = 0;

    int result_test_bit_per_pixel = test_bit_per_pixel();
    num_total++;

    int result_test_8bit = test_8bit();
    num_total++;

    int result_test_10bit = test_10bit();
    num_total++;

    int result_test_12bit = test_12bit();
    num_total++;

    if (!result_test_bit_per_pixel) {
        printf("test_bit_per_pixel failed");
        num_fail++;
    }

    if (!result_test_8bit) {
        printf("test_8bit failed");
        num_fail++;
    }

    if (!result_test_10bit) {
        printf("test_10bit failed");
        num_fail++;
    }

    if (!result_test_12bit) {
        printf("test_12bit failed");
        num_fail++;
    }

    print_common_8bit();
    print_common_10bit();
    print_common_12bit();
    print_common_packed();

    printf("Tests failed: %d out of %d\n", num_fail, num_total);

	return 0;
}
