#!/bin/sh

prefix=/home/pacaud/Sources/INSTALL
exec_prefix=/home/pacaud/Sources/INSTALL

export PATH=${exec_prefix}/bin:${PATH}

gst-launch-1.0 --gst-plugin-load=../gst/.libs/libgstaravis-0.6.so -v $*

