#!/bin/sh

prefix=/home/pacaud/Sources/INSTALL
exec_prefix=/home/pacaud/Sources/INSTALL

export PATH=${exec_prefix}/bin:${PATH}

LD_PRELOAD=../src/.libs/libaravis.so gst-inspect --gst-plugin-load=../gst/.libs/libgstaravis.so $*

