name: Clang Format Check

on:
  pull_request:
    paths:
      - '**/*.cpp'
      - '**/*.c'
      - '**/*.h'

jobs:
  clang-format:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Fetch pull request changes
      run: git fetch origin +refs/pull/${{ github.event.pull_request.number }}/merge

    - name: Generate diff of changes
      run: git diff origin/main...HEAD > changes.diff

    - name: Run clang-format-diff
      run: |
        cat changes.diff | clang-format-diff -p1 -i

    - name: Check for formatting changes
      run: |
        if ! git diff --exit-code
        then
          echo "Clang-format found issues in the following files:"
          git diff --name-only
          exit 1
        fi
